#org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
#android.useAndroidX=true
#android.enableJetifier=true


org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableJetifier=true

# ? Lock NDK version (make sure this version is installed in SDK Manager)
android.ndkVersion=25.2.9519653

# (Optional) Improve build speed
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
